name: Run Python Script - Main

on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with: 
            python-version: '3.11'

      - name: Run Python Script
        run: |         
          python -m pip install requests
          python FileName.py
          
      - name: commit files & push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update my_media_playlist.m3u file"
          git push origin HEAD:main
          
      
          

            
         
