
name: Clone Private Repository Workflow

on:
  push:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
    
  job-public-repo-ubuntu:
    runs-on: ubuntu-latest
    steps:
      
      - name: Clone rawsand/0xtuzljoN PRIVATE repository
        uses: rawsand/clone-github-repo-action@main
        with:
          owner: 'rawsand'
          branch: master
          repository: '0xtuzljoN'
          access-token: ${{ secrets.ACCESS_TOKEN }}
      
      - name: Access cloned repository content
        run: |
          echo "ROOT"
          ls -la
          echo "CLONED REPO"
          cd 0xtuzljoN
          ls -la

  job-public-repo-macos:
    runs-on: macos-latest
    steps:
      
      - name: Clone rawsand/0xtuzljoN PRIVATE repository
        uses: rawsand/clone-github-repo-action@main
        with:
          owner: 'rawsand'
          branch: master
          repository: '0xtuzljoN'
          access-token: ${{ secrets.DEST_REPO_TOKEN }}
      
      - name: Access cloned repository content
        run: |
          echo "ROOT"
          ls -la
          echo "CLONED REPO"
          cd 0xtuzljoN
          ls -la

  job-public-repo-window:
    runs-on: windows-latest
    steps:
      
      - name: Clone rawsand/0xtuzljoN PRIVATE repository
        uses: rawsand/clone-github-repo-action@main
        with:
          owner: 'rawsand'
          branch: master
          repository: '0xtuzljoN'
          access-token: ${{ secrets.DEST_REPO_TOKEN }}
      
      - name: Access cloned repository content
        run: |
          echo "ROOT"
          ls -la
          echo "CLONED REPO"
          cd 0xtuzljoN
          ls -la
        shell: bash
