name: Trigger Secret PHP Script

on:
  schedule:
    # Runs every 5 hours
    - cron: '30 2 * * *'
    
  # Allows you to manually trigger the workflow from the Actions tab anytime
  workflow_dispatch:

jobs:
  trigger-script:
    runs-on: ubuntu-latest

    steps:
    - name: Ping Remote Server
      env:
        # This maps your GitHub secret to an environment variable in the runner
        TARGET_URL: ${{ secrets.MY_EPG_PHP_URL }}
      run: |
        curl -I "$TARGET_URL"
