name: Trigger Secret PHP Script

on:
  schedule:
    # Runs 8 AM IST
    - cron: '40 */9 * * *'
    
  # Allows you to manually trigger the workflow from the Actions tab anytime
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pip install requests

      - name: Run playlist filter        
        run: |          
          python final_epg1.py
          
      - name: Commit filtered playlist
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add filtered.xml.gz
          git commit -m "Update playlist"
          git push
